/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminPassesRouteImport } from './routes/_authenticated/admin/passes'
import { Route as AuthenticatedAdminReservationsRouteImport } from './routes/_authenticated/admin/reservations'
import { Route as AuthenticatedAdminReservationsAttendanceRouteImport } from './routes/_authenticated/admin/reservations-attendance'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminActivitiesIndexRouteImport } from './routes/_authenticated/admin/activities/index'
import { Route as AuthenticatedAdminActivitiesIdRouteImport } from './routes/_authenticated/admin/activities/$id'
import { Route as AuthenticatedAdminActivitiesCompletedRouteImport } from './routes/_authenticated/admin/activities/completed'
import { Route as AuthenticatedAdminDogsIndexRouteImport } from './routes/_authenticated/admin/dogs/index'
import { Route as AuthenticatedAdminDogsInactiveRouteImport } from './routes/_authenticated/admin/dogs/inactive'
import { Route as AuthenticatedAdminPendingReservationsIndexRouteImport } from './routes/_authenticated/admin/pending-reservations/index'
import { Route as AuthenticatedAdminTodayClassesIndexRouteImport } from './routes/_authenticated/admin/today-classes/index'
import { Route as AuthenticatedAdminTodayClassesIdRouteImport } from './routes/_authenticated/admin/today-classes/$id'

const AuthenticatedActiveDogsLazyRouteImport = createFileRoute(
  '/_authenticated/active-dogs',
)()
const AuthenticatedCalendarLazyRouteImport = createFileRoute(
  '/_authenticated/calendar',
)()
const AuthenticatedDogsLazyRouteImport = createFileRoute(
  '/_authenticated/dogs',
)()
const AuthenticatedIncompatibilitiesLazyRouteImport = createFileRoute(
  '/_authenticated/incompatibilities',
)()
const AuthenticatedPassesLazyRouteImport = createFileRoute(
  '/_authenticated/passes',
)()
const AuthenticatedProfileLazyRouteImport = createFileRoute(
  '/_authenticated/profile',
)()
const AuthenticatedReservationsLazyRouteImport = createFileRoute(
  '/_authenticated/reservations',
)()
const AuthLoginLazyRouteImport = createFileRoute('/auth/login')()
const AuthRegisterLazyRouteImport = createFileRoute('/auth/register')()
const AuthenticatedDogDetailIdLazyRouteImport = createFileRoute(
  '/_authenticated/dog-detail/$id',
)()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedActiveDogsLazyRoute =
  AuthenticatedActiveDogsLazyRouteImport.update({
    id: '/active-dogs',
    path: '/active-dogs',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/active-dogs.lazy').then((d) => d.Route),
  )
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalendarLazyRoute =
  AuthenticatedCalendarLazyRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/calendar.lazy').then((d) => d.Route),
  )
const AuthenticatedDogsLazyRoute = AuthenticatedDogsLazyRouteImport.update({
  id: '/dogs',
  path: '/dogs',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/dogs.lazy').then((d) => d.Route),
)
const AuthenticatedIncompatibilitiesLazyRoute =
  AuthenticatedIncompatibilitiesLazyRouteImport.update({
    id: '/incompatibilities',
    path: '/incompatibilities',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/incompatibilities.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedPassesLazyRoute = AuthenticatedPassesLazyRouteImport.update({
  id: '/passes',
  path: '/passes',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/passes.lazy').then((d) => d.Route),
)
const AuthenticatedProfileLazyRoute =
  AuthenticatedProfileLazyRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/profile.lazy').then((d) => d.Route),
  )
const AuthenticatedReservationsLazyRoute =
  AuthenticatedReservationsLazyRouteImport.update({
    id: '/reservations',
    path: '/reservations',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/reservations.lazy').then((d) => d.Route),
  )
const AuthLoginLazyRoute = AuthLoginLazyRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/auth.login.lazy').then((d) => d.Route))
const AuthRegisterLazyRoute = AuthRegisterLazyRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/auth.register.lazy').then((d) => d.Route))
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPassesRoute =
  AuthenticatedAdminPassesRouteImport.update({
    id: '/passes',
    path: '/passes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReservationsRoute =
  AuthenticatedAdminReservationsRouteImport.update({
    id: '/reservations',
    path: '/reservations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReservationsAttendanceRoute =
  AuthenticatedAdminReservationsAttendanceRouteImport.update({
    id: '/reservations-attendance',
    path: '/reservations-attendance',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedDogDetailIdLazyRoute =
  AuthenticatedDogDetailIdLazyRouteImport.update({
    id: '/dog-detail/$id',
    path: '/dog-detail/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/dog-detail.$id.lazy').then((d) => d.Route),
  )
const AuthenticatedAdminActivitiesIndexRoute =
  AuthenticatedAdminActivitiesIndexRouteImport.update({
    id: '/activities/',
    path: '/activities/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminActivitiesIdRoute =
  AuthenticatedAdminActivitiesIdRouteImport.update({
    id: '/activities/$id',
    path: '/activities/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminActivitiesCompletedRoute =
  AuthenticatedAdminActivitiesCompletedRouteImport.update({
    id: '/activities/completed',
    path: '/activities/completed',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDogsIndexRoute =
  AuthenticatedAdminDogsIndexRouteImport.update({
    id: '/dogs/',
    path: '/dogs/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDogsInactiveRoute =
  AuthenticatedAdminDogsInactiveRouteImport.update({
    id: '/dogs/inactive',
    path: '/dogs/inactive',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPendingReservationsIndexRoute =
  AuthenticatedAdminPendingReservationsIndexRouteImport.update({
    id: '/pending-reservations/',
    path: '/pending-reservations/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTodayClassesIndexRoute =
  AuthenticatedAdminTodayClassesIndexRouteImport.update({
    id: '/today-classes/',
    path: '/today-classes/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTodayClassesIdRoute =
  AuthenticatedAdminTodayClassesIdRouteImport.update({
    id: '/today-classes/$id',
    path: '/today-classes/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/active-dogs': typeof AuthenticatedActiveDogsLazyRoute
  '/calendar': typeof AuthenticatedCalendarLazyRoute
  '/dogs': typeof AuthenticatedDogsLazyRoute
  '/incompatibilities': typeof AuthenticatedIncompatibilitiesLazyRoute
  '/passes': typeof AuthenticatedPassesLazyRoute
  '/profile': typeof AuthenticatedProfileLazyRoute
  '/reservations': typeof AuthenticatedReservationsLazyRoute
  '/auth/login': typeof AuthLoginLazyRoute
  '/auth/register': typeof AuthRegisterLazyRoute
  '/admin/passes': typeof AuthenticatedAdminPassesRoute
  '/admin/reservations': typeof AuthenticatedAdminReservationsRoute
  '/admin/reservations-attendance': typeof AuthenticatedAdminReservationsAttendanceRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/dog-detail/$id': typeof AuthenticatedDogDetailIdLazyRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/activities/$id': typeof AuthenticatedAdminActivitiesIdRoute
  '/admin/activities/completed': typeof AuthenticatedAdminActivitiesCompletedRoute
  '/admin/dogs/inactive': typeof AuthenticatedAdminDogsInactiveRoute
  '/admin/today-classes/$id': typeof AuthenticatedAdminTodayClassesIdRoute
  '/admin/activities/': typeof AuthenticatedAdminActivitiesIndexRoute
  '/admin/dogs/': typeof AuthenticatedAdminDogsIndexRoute
  '/admin/pending-reservations/': typeof AuthenticatedAdminPendingReservationsIndexRoute
  '/admin/today-classes/': typeof AuthenticatedAdminTodayClassesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/active-dogs': typeof AuthenticatedActiveDogsLazyRoute
  '/calendar': typeof AuthenticatedCalendarLazyRoute
  '/dogs': typeof AuthenticatedDogsLazyRoute
  '/incompatibilities': typeof AuthenticatedIncompatibilitiesLazyRoute
  '/passes': typeof AuthenticatedPassesLazyRoute
  '/profile': typeof AuthenticatedProfileLazyRoute
  '/reservations': typeof AuthenticatedReservationsLazyRoute
  '/auth/login': typeof AuthLoginLazyRoute
  '/auth/register': typeof AuthRegisterLazyRoute
  '/admin/passes': typeof AuthenticatedAdminPassesRoute
  '/admin/reservations': typeof AuthenticatedAdminReservationsRoute
  '/admin/reservations-attendance': typeof AuthenticatedAdminReservationsAttendanceRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/dog-detail/$id': typeof AuthenticatedDogDetailIdLazyRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/activities/$id': typeof AuthenticatedAdminActivitiesIdRoute
  '/admin/activities/completed': typeof AuthenticatedAdminActivitiesCompletedRoute
  '/admin/dogs/inactive': typeof AuthenticatedAdminDogsInactiveRoute
  '/admin/today-classes/$id': typeof AuthenticatedAdminTodayClassesIdRoute
  '/admin/activities': typeof AuthenticatedAdminActivitiesIndexRoute
  '/admin/dogs': typeof AuthenticatedAdminDogsIndexRoute
  '/admin/pending-reservations': typeof AuthenticatedAdminPendingReservationsIndexRoute
  '/admin/today-classes': typeof AuthenticatedAdminTodayClassesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/active-dogs': typeof AuthenticatedActiveDogsLazyRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarLazyRoute
  '/_authenticated/dogs': typeof AuthenticatedDogsLazyRoute
  '/_authenticated/incompatibilities': typeof AuthenticatedIncompatibilitiesLazyRoute
  '/_authenticated/passes': typeof AuthenticatedPassesLazyRoute
  '/_authenticated/profile': typeof AuthenticatedProfileLazyRoute
  '/_authenticated/reservations': typeof AuthenticatedReservationsLazyRoute
  '/auth/login': typeof AuthLoginLazyRoute
  '/auth/register': typeof AuthRegisterLazyRoute
  '/_authenticated/admin/passes': typeof AuthenticatedAdminPassesRoute
  '/_authenticated/admin/reservations': typeof AuthenticatedAdminReservationsRoute
  '/_authenticated/admin/reservations-attendance': typeof AuthenticatedAdminReservationsAttendanceRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/dog-detail/$id': typeof AuthenticatedDogDetailIdLazyRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/activities/$id': typeof AuthenticatedAdminActivitiesIdRoute
  '/_authenticated/admin/activities/completed': typeof AuthenticatedAdminActivitiesCompletedRoute
  '/_authenticated/admin/dogs/inactive': typeof AuthenticatedAdminDogsInactiveRoute
  '/_authenticated/admin/today-classes/$id': typeof AuthenticatedAdminTodayClassesIdRoute
  '/_authenticated/admin/activities/': typeof AuthenticatedAdminActivitiesIndexRoute
  '/_authenticated/admin/dogs/': typeof AuthenticatedAdminDogsIndexRoute
  '/_authenticated/admin/pending-reservations/': typeof AuthenticatedAdminPendingReservationsIndexRoute
  '/_authenticated/admin/today-classes/': typeof AuthenticatedAdminTodayClassesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/active-dogs'
    | '/calendar'
    | '/dogs'
    | '/incompatibilities'
    | '/passes'
    | '/profile'
    | '/reservations'
    | '/auth/login'
    | '/auth/register'
    | '/admin/passes'
    | '/admin/reservations'
    | '/admin/reservations-attendance'
    | '/admin/users'
    | '/dog-detail/$id'
    | '/admin/'
    | '/admin/activities/$id'
    | '/admin/activities/completed'
    | '/admin/dogs/inactive'
    | '/admin/today-classes/$id'
    | '/admin/activities/'
    | '/admin/dogs/'
    | '/admin/pending-reservations/'
    | '/admin/today-classes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/active-dogs'
    | '/calendar'
    | '/dogs'
    | '/incompatibilities'
    | '/passes'
    | '/profile'
    | '/reservations'
    | '/auth/login'
    | '/auth/register'
    | '/admin/passes'
    | '/admin/reservations'
    | '/admin/reservations-attendance'
    | '/admin/users'
    | '/dog-detail/$id'
    | '/admin'
    | '/admin/activities/$id'
    | '/admin/activities/completed'
    | '/admin/dogs/inactive'
    | '/admin/today-classes/$id'
    | '/admin/activities'
    | '/admin/dogs'
    | '/admin/pending-reservations'
    | '/admin/today-classes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/admin'
    | '/_authenticated/active-dogs'
    | '/_authenticated/calendar'
    | '/_authenticated/dogs'
    | '/_authenticated/incompatibilities'
    | '/_authenticated/passes'
    | '/_authenticated/profile'
    | '/_authenticated/reservations'
    | '/auth/login'
    | '/auth/register'
    | '/_authenticated/admin/passes'
    | '/_authenticated/admin/reservations'
    | '/_authenticated/admin/reservations-attendance'
    | '/_authenticated/admin/users'
    | '/_authenticated/dog-detail/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/activities/$id'
    | '/_authenticated/admin/activities/completed'
    | '/_authenticated/admin/dogs/inactive'
    | '/_authenticated/admin/today-classes/$id'
    | '/_authenticated/admin/activities/'
    | '/_authenticated/admin/dogs/'
    | '/_authenticated/admin/pending-reservations/'
    | '/_authenticated/admin/today-classes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthLoginLazyRoute: typeof AuthLoginLazyRoute
  AuthRegisterLazyRoute: typeof AuthRegisterLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/active-dogs': {
      id: '/_authenticated/active-dogs'
      path: '/active-dogs'
      fullPath: '/active-dogs'
      preLoaderRoute: typeof AuthenticatedActiveDogsLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dogs': {
      id: '/_authenticated/dogs'
      path: '/dogs'
      fullPath: '/dogs'
      preLoaderRoute: typeof AuthenticatedDogsLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/incompatibilities': {
      id: '/_authenticated/incompatibilities'
      path: '/incompatibilities'
      fullPath: '/incompatibilities'
      preLoaderRoute: typeof AuthenticatedIncompatibilitiesLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/passes': {
      id: '/_authenticated/passes'
      path: '/passes'
      fullPath: '/passes'
      preLoaderRoute: typeof AuthenticatedPassesLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reservations': {
      id: '/_authenticated/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof AuthenticatedReservationsLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/passes': {
      id: '/_authenticated/admin/passes'
      path: '/passes'
      fullPath: '/admin/passes'
      preLoaderRoute: typeof AuthenticatedAdminPassesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reservations': {
      id: '/_authenticated/admin/reservations'
      path: '/reservations'
      fullPath: '/admin/reservations'
      preLoaderRoute: typeof AuthenticatedAdminReservationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reservations-attendance': {
      id: '/_authenticated/admin/reservations-attendance'
      path: '/reservations-attendance'
      fullPath: '/admin/reservations-attendance'
      preLoaderRoute: typeof AuthenticatedAdminReservationsAttendanceRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/dog-detail/$id': {
      id: '/_authenticated/dog-detail/$id'
      path: '/dog-detail/$id'
      fullPath: '/dog-detail/$id'
      preLoaderRoute: typeof AuthenticatedDogDetailIdLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/activities/': {
      id: '/_authenticated/admin/activities/'
      path: '/activities'
      fullPath: '/admin/activities/'
      preLoaderRoute: typeof AuthenticatedAdminActivitiesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/activities/$id': {
      id: '/_authenticated/admin/activities/$id'
      path: '/activities/$id'
      fullPath: '/admin/activities/$id'
      preLoaderRoute: typeof AuthenticatedAdminActivitiesIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/activities/completed': {
      id: '/_authenticated/admin/activities/completed'
      path: '/activities/completed'
      fullPath: '/admin/activities/completed'
      preLoaderRoute: typeof AuthenticatedAdminActivitiesCompletedRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dogs/': {
      id: '/_authenticated/admin/dogs/'
      path: '/dogs'
      fullPath: '/admin/dogs/'
      preLoaderRoute: typeof AuthenticatedAdminDogsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dogs/inactive': {
      id: '/_authenticated/admin/dogs/inactive'
      path: '/dogs/inactive'
      fullPath: '/admin/dogs/inactive'
      preLoaderRoute: typeof AuthenticatedAdminDogsInactiveRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pending-reservations/': {
      id: '/_authenticated/admin/pending-reservations/'
      path: '/pending-reservations'
      fullPath: '/admin/pending-reservations/'
      preLoaderRoute: typeof AuthenticatedAdminPendingReservationsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/today-classes/': {
      id: '/_authenticated/admin/today-classes/'
      path: '/today-classes'
      fullPath: '/admin/today-classes/'
      preLoaderRoute: typeof AuthenticatedAdminTodayClassesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/today-classes/$id': {
      id: '/_authenticated/admin/today-classes/$id'
      path: '/today-classes/$id'
      fullPath: '/admin/today-classes/$id'
      preLoaderRoute: typeof AuthenticatedAdminTodayClassesIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminPassesRoute: typeof AuthenticatedAdminPassesRoute
  AuthenticatedAdminReservationsRoute: typeof AuthenticatedAdminReservationsRoute
  AuthenticatedAdminReservationsAttendanceRoute: typeof AuthenticatedAdminReservationsAttendanceRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminActivitiesIdRoute: typeof AuthenticatedAdminActivitiesIdRoute
  AuthenticatedAdminActivitiesCompletedRoute: typeof AuthenticatedAdminActivitiesCompletedRoute
  AuthenticatedAdminDogsInactiveRoute: typeof AuthenticatedAdminDogsInactiveRoute
  AuthenticatedAdminTodayClassesIdRoute: typeof AuthenticatedAdminTodayClassesIdRoute
  AuthenticatedAdminActivitiesIndexRoute: typeof AuthenticatedAdminActivitiesIndexRoute
  AuthenticatedAdminDogsIndexRoute: typeof AuthenticatedAdminDogsIndexRoute
  AuthenticatedAdminPendingReservationsIndexRoute: typeof AuthenticatedAdminPendingReservationsIndexRoute
  AuthenticatedAdminTodayClassesIndexRoute: typeof AuthenticatedAdminTodayClassesIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminPassesRoute: AuthenticatedAdminPassesRoute,
  AuthenticatedAdminReservationsRoute: AuthenticatedAdminReservationsRoute,
  AuthenticatedAdminReservationsAttendanceRoute:
    AuthenticatedAdminReservationsAttendanceRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminActivitiesIdRoute: AuthenticatedAdminActivitiesIdRoute,
  AuthenticatedAdminActivitiesCompletedRoute:
    AuthenticatedAdminActivitiesCompletedRoute,
  AuthenticatedAdminDogsInactiveRoute: AuthenticatedAdminDogsInactiveRoute,
  AuthenticatedAdminTodayClassesIdRoute: AuthenticatedAdminTodayClassesIdRoute,
  AuthenticatedAdminActivitiesIndexRoute:
    AuthenticatedAdminActivitiesIndexRoute,
  AuthenticatedAdminDogsIndexRoute: AuthenticatedAdminDogsIndexRoute,
  AuthenticatedAdminPendingReservationsIndexRoute:
    AuthenticatedAdminPendingReservationsIndexRoute,
  AuthenticatedAdminTodayClassesIndexRoute:
    AuthenticatedAdminTodayClassesIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedActiveDogsLazyRoute: typeof AuthenticatedActiveDogsLazyRoute
  AuthenticatedCalendarLazyRoute: typeof AuthenticatedCalendarLazyRoute
  AuthenticatedDogsLazyRoute: typeof AuthenticatedDogsLazyRoute
  AuthenticatedIncompatibilitiesLazyRoute: typeof AuthenticatedIncompatibilitiesLazyRoute
  AuthenticatedPassesLazyRoute: typeof AuthenticatedPassesLazyRoute
  AuthenticatedProfileLazyRoute: typeof AuthenticatedProfileLazyRoute
  AuthenticatedReservationsLazyRoute: typeof AuthenticatedReservationsLazyRoute
  AuthenticatedDogDetailIdLazyRoute: typeof AuthenticatedDogDetailIdLazyRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedActiveDogsLazyRoute: AuthenticatedActiveDogsLazyRoute,
  AuthenticatedCalendarLazyRoute: AuthenticatedCalendarLazyRoute,
  AuthenticatedDogsLazyRoute: AuthenticatedDogsLazyRoute,
  AuthenticatedIncompatibilitiesLazyRoute:
    AuthenticatedIncompatibilitiesLazyRoute,
  AuthenticatedPassesLazyRoute: AuthenticatedPassesLazyRoute,
  AuthenticatedProfileLazyRoute: AuthenticatedProfileLazyRoute,
  AuthenticatedReservationsLazyRoute: AuthenticatedReservationsLazyRoute,
  AuthenticatedDogDetailIdLazyRoute: AuthenticatedDogDetailIdLazyRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthLoginLazyRoute: AuthLoginLazyRoute,
  AuthRegisterLazyRoute: AuthRegisterLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
