// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/dogs": {
            "get": {
                "description": "Returns a paginated list of all dogs across all owners. Limit defaults to 50 and is capped at 100. Offset defaults to 0.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dogs"
                ],
                "summary": "List all dogs in the system",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Maximum number of dogs to return (default 50, max 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of dogs to skip for pagination (default 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of dogs with pagination metadata",
                        "schema": {
                            "$ref": "#/definitions/handler.listDogsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new dog record owned by a user. The new resource URL is returned in the Location header.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dogs"
                ],
                "summary": "Register a new dog",
                "parameters": [
                    {
                        "description": "Dog to register",
                        "name": "dog",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.registerDogRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Dog created successfully",
                        "schema": {
                            "$ref": "#/definitions/handler.registerDogResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body, missing fields, validation error, or invalid user_id",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "409": {
                        "description": "Passport already exists",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/dogs/active": {
            "get": {
                "description": "Returns a paginated list of dogs whose is_active is true. Limit defaults to 50, capped at 100. Offset defaults to 0.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dogs"
                ],
                "summary": "List active dogs",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Maximum number of dogs to return (default 50, max 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of dogs to skip for pagination (default 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.listDogsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/dogs/age/{bracket}": {
            "get": {
                "description": "Returns a paginated list of dogs whose age_bracket matches :bracket. Limit defaults to 50, capped at 100. Offset defaults to 0.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dogs"
                ],
                "summary": "List dogs filtered by age bracket",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Age bracket: CHILDREN, TEENAGER, SEMI_ADULT, ADULT, UNKNOWN",
                        "name": "bracket",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Maximum number of dogs to return (default 50, max 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of dogs to skip for pagination (default 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.listDogsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/dogs/breed/{breed}": {
            "get": {
                "description": "Returns a paginated list of dogs whose breed matches :breed. Limit defaults to 50, capped at 100. Offset defaults to 0.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dogs"
                ],
                "summary": "List dogs filtered by breed",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Breed name (exact match)",
                        "name": "breed",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Maximum number of dogs to return (default 50, max 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of dogs to skip for pagination (default 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.listDogsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/dogs/heat/{value}": {
            "get": {
                "description": "Returns a paginated list of dogs whose heat flag matches :value. Limit defaults to 50, capped at 100. Offset defaults to 0.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dogs"
                ],
                "summary": "List dogs filtered by heat status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Boolean value: true or false",
                        "name": "value",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Maximum number of dogs to return (default 50, max 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of dogs to skip for pagination (default 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.listDogsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/dogs/incompatibility/{incompat_id}": {
            "get": {
                "description": "Returns a paginated list of dogs attached to the given incompatibility id. Limit defaults to 50, capped at 100. Offset defaults to 0.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dogs"
                ],
                "summary": "List dogs that have a specific incompatibility",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of the incompatibility",
                        "name": "incompat_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Maximum number of dogs to return (default 50, max 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of dogs to skip for pagination (default 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.listDogsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/dogs/is_active/{value}": {
            "get": {
                "description": "Returns a paginated list of dogs whose is_active matches :value (true or false). Limit defaults to 50, capped at 100. Offset defaults to 0.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dogs"
                ],
                "summary": "List dogs filtered by is_active",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Boolean value: true or false",
                        "name": "value",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Maximum number of dogs to return (default 50, max 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of dogs to skip for pagination (default 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.listDogsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/dogs/neutered/{value}": {
            "get": {
                "description": "Returns a paginated list of dogs whose neutered flag matches :value. Limit defaults to 50, capped at 100. Offset defaults to 0.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dogs"
                ],
                "summary": "List dogs filtered by neutered status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Boolean value: true or false",
                        "name": "value",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Maximum number of dogs to return (default 50, max 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of dogs to skip for pagination (default 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.listDogsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/dogs/owner/{owner_id}": {
            "get": {
                "description": "Returns a paginated list of dogs belonging to the given owner. Limit defaults to 50 and is capped at 100. Offset defaults to 0.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dogs"
                ],
                "summary": "List dogs owned by a specific user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of the owner user",
                        "name": "owner_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Maximum number of dogs to return (default 50, max 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of dogs to skip for pagination (default 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of dogs with pagination metadata",
                        "schema": {
                            "$ref": "#/definitions/handler.listDogsResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid owner_id",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/dogs/sex/{sex}": {
            "get": {
                "description": "Returns a paginated list of dogs whose sex matches :sex. Limit defaults to 50, capped at 100. Offset defaults to 0.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dogs"
                ],
                "summary": "List dogs filtered by sex",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sex: MALE or FEMALE",
                        "name": "sex",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Maximum number of dogs to return (default 50, max 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of dogs to skip for pagination (default 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.listDogsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/dogs/size/{bracket}": {
            "get": {
                "description": "Returns a paginated list of dogs whose size_bracket matches :bracket. Limit defaults to 50, capped at 100. Offset defaults to 0.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dogs"
                ],
                "summary": "List dogs filtered by size bracket",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Size bracket: MINI, MEDIUM, LARGE, UNKNOWN",
                        "name": "bracket",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Maximum number of dogs to return (default 50, max 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of dogs to skip for pagination (default 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.listDogsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/dogs/{id}": {
            "delete": {
                "description": "Removes a dog by id. Associated dog_incompatibilities and reservations rows are deleted automatically by the database (ON DELETE CASCADE). Returns 404 if the dog does not exist.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dogs"
                ],
                "summary": "Delete a dog",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Dog ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Applies a partial update to an existing dog. Only the fields present in the request body are modified; omitted fields are preserved. An empty body is a no-op and returns 200 without touching the database. Designed for fixing typos (e.g. \"Labarador\" -\u003e \"Labrador\") or correcting registration mistakes.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dogs"
                ],
                "summary": "Patch a dog (partial update)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Dog ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Fields to patch (only the fields you want to change)",
                        "name": "dog",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.modifyDogRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Dog patched (or no-op if body was empty)",
                        "schema": {
                            "$ref": "#/definitions/handler.modifyDogResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid id, invalid request body, or validation error (e.g. empty name, negative weight, invalid sex)",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Dog not found",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "409": {
                        "description": "Passport already exists",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/dogs/{id}/incompatibilities": {
            "post": {
                "description": "Idempotently attaches an existing incompatibility (looked up by id) to a dog. If the dog already has that incompatibility, returns 200 with ` + "`" + `added: false` + "`" + ` and the current list (no DB write). Otherwise persists the change and returns 201 with ` + "`" + `added: true` + "`" + ` and the updated list. Both the dog and the incompatibility must exist.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dogs"
                ],
                "summary": "Add an incompatibility to a dog",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Dog ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Incompatibility to attach",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.addIncompatibilityRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Incompatibility was already attached (added=false, idempotent no-op)",
                        "schema": {
                            "$ref": "#/definitions/handler.addIncompatibilityResponse"
                        }
                    },
                    "201": {
                        "description": "Incompatibility newly attached (added=true)",
                        "schema": {
                            "$ref": "#/definitions/handler.addIncompatibilityResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid id, invalid body, or validation error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Dog or incompatibility not found",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/dogs/{id}/incompatibilities/{incompatibility_id}": {
            "delete": {
                "description": "Idempotently detaches an existing incompatibility (looked up by id) from a dog. If the dog does not have that incompatibility, returns 200 with the current list (no DB write). Otherwise persists the change and returns 200 with the updated list. Both dog and incompatibility must exist; 404 otherwise.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dogs"
                ],
                "summary": "Remove an incompatibility from a dog",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Dog ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Incompatibility ID",
                        "name": "incompatibility_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Incompatibility removed (or no-op if not present), with the current list",
                        "schema": {
                            "$ref": "#/definitions/handler.removeIncompatibilityResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid id or incompatibility_id",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Dog not found",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/incompatibilities": {
            "get": {
                "description": "Returns all incompatibilities, optionally filtered by level.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "incompatibilities"
                ],
                "summary": "List incompatibilities",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by level (ABSOLUTA, MEDIA, BAJA)",
                        "name": "level",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of incompatibilities",
                        "schema": {
                            "$ref": "#/definitions/handler.listIncompatibilitiesResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid level filter",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new incompatibility category. The name must be unique (case-insensitive).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "incompatibilities"
                ],
                "summary": "Register a new incompatibility",
                "parameters": [
                    {
                        "description": "Incompatibility to create",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.registerIncompatibilityRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Incompatibility created",
                        "schema": {
                            "$ref": "#/definitions/handler.registerIncompatibilityResponse"
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "409": {
                        "description": "Name already exists",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/incompatibilities/{id}": {
            "get": {
                "description": "Returns a single incompatibility by its ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "incompatibilities"
                ],
                "summary": "Get incompatibility by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Incompatibility ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Incompatibility found",
                        "schema": {
                            "$ref": "#/definitions/handler.incompatibilityResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid id",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Incompatibility not found",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes an incompatibility. Fails with 409 if it is still referenced by any dog.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "incompatibilities"
                ],
                "summary": "Delete an incompatibility",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Incompatibility ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No content"
                    },
                    "400": {
                        "description": "Invalid id",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Incompatibility not found",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "409": {
                        "description": "Incompatibility is in use by at least one dog",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Partially updates an incompatibility (name and/or level). An empty body is a no-op.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "incompatibilities"
                ],
                "summary": "Patch an incompatibility",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Incompatibility ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Fields to patch",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.modifyIncompatibilityRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Updated incompatibility",
                        "schema": {
                            "$ref": "#/definitions/handler.incompatibilityResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid id, body, or validation error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Incompatibility not found",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "409": {
                        "description": "Name already exists",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.addIncompatibilityRequest": {
            "type": "object",
            "required": [
                "incompatibility_id"
            ],
            "properties": {
                "incompatibility_id": {
                    "type": "integer",
                    "example": 3
                }
            }
        },
        "handler.addIncompatibilityResponse": {
            "type": "object",
            "properties": {
                "added": {
                    "type": "boolean",
                    "example": true
                },
                "dog_id": {
                    "type": "integer",
                    "example": 42
                },
                "incompatibilities": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.incompatibilityDTO"
                    }
                }
            }
        },
        "handler.dogDTO": {
            "type": "object",
            "properties": {
                "age_in_months": {
                    "type": "integer",
                    "example": 24
                },
                "breed": {
                    "type": "string",
                    "example": "Labrador"
                },
                "educator_notes": {
                    "type": "string",
                    "example": ""
                },
                "heat": {
                    "type": "boolean",
                    "example": false
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "medical_notes": {
                    "type": "string",
                    "example": ""
                },
                "name": {
                    "type": "string",
                    "example": "Luna"
                },
                "neutered": {
                    "type": "boolean",
                    "example": false
                },
                "passport": {
                    "type": "string",
                    "example": "ES-12345"
                },
                "photo_url": {
                    "type": "string",
                    "example": ""
                },
                "sex": {
                    "type": "string",
                    "example": "FEMALE"
                },
                "user_id": {
                    "type": "integer",
                    "example": 1
                },
                "weight_kg": {
                    "type": "number",
                    "example": 22.5
                }
            }
        },
        "handler.errorResponse": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "string",
                    "example": "Field 'breed' is required"
                },
                "error": {
                    "type": "string",
                    "example": "validation"
                },
                "field": {
                    "type": "string",
                    "example": "breed"
                }
            }
        },
        "handler.incompatibilityDTO": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 3
                },
                "level": {
                    "type": "string",
                    "example": "ABSOLUTA"
                },
                "name": {
                    "type": "string",
                    "example": "Reactivo a machos enteros"
                }
            }
        },
        "handler.incompatibilityResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 3
                },
                "level": {
                    "type": "string",
                    "example": "BAJA"
                },
                "name": {
                    "type": "string",
                    "example": "Miedo a petardos"
                }
            }
        },
        "handler.listDogsResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer",
                    "example": 1
                },
                "dogs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.dogDTO"
                    }
                },
                "limit": {
                    "type": "integer",
                    "example": 50
                },
                "offset": {
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "handler.listIncompatibilitiesResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer",
                    "example": 3
                },
                "incompatibilities": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.incompatibilityDTO"
                    }
                }
            }
        },
        "handler.modifyDogRequest": {
            "type": "object",
            "properties": {
                "age_in_months": {
                    "type": "integer",
                    "example": 24
                },
                "breed": {
                    "type": "string",
                    "example": "Labrador"
                },
                "educator_notes": {
                    "type": "string",
                    "example": ""
                },
                "heat": {
                    "type": "boolean",
                    "example": false
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "medical_notes": {
                    "type": "string",
                    "example": ""
                },
                "name": {
                    "type": "string",
                    "example": "Buddie"
                },
                "neutered": {
                    "type": "boolean",
                    "example": true
                },
                "passport": {
                    "type": "string",
                    "example": "ES-12345"
                },
                "photo_url": {
                    "type": "string",
                    "example": ""
                },
                "sex": {
                    "type": "string",
                    "example": "FEMALE"
                },
                "weight_kg": {
                    "type": "number",
                    "example": 22.5
                }
            }
        },
        "handler.modifyDogResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 42
                }
            }
        },
        "handler.modifyIncompatibilityRequest": {
            "type": "object",
            "properties": {
                "level": {
                    "type": "string",
                    "example": "ABSOLUTA"
                },
                "name": {
                    "type": "string",
                    "example": "Miedo a petardos y cohetes"
                }
            }
        },
        "handler.registerDogRequest": {
            "type": "object",
            "required": [
                "age_in_months",
                "breed",
                "name",
                "passport",
                "sex",
                "user_id",
                "weight_kg"
            ],
            "properties": {
                "age_in_months": {
                    "type": "integer",
                    "example": 24
                },
                "breed": {
                    "type": "string",
                    "maxLength": 120,
                    "minLength": 1,
                    "example": "Labrador"
                },
                "name": {
                    "type": "string",
                    "maxLength": 120,
                    "minLength": 1,
                    "example": "Luna"
                },
                "passport": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 1,
                    "example": "ES-12345"
                },
                "sex": {
                    "type": "string",
                    "enum": [
                        "MALE",
                        "FEMALE"
                    ],
                    "example": "FEMALE"
                },
                "user_id": {
                    "type": "integer",
                    "example": 1
                },
                "weight_kg": {
                    "type": "number",
                    "example": 22.5
                }
            }
        },
        "handler.registerDogResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 42
                }
            }
        },
        "handler.registerIncompatibilityRequest": {
            "type": "object",
            "required": [
                "level",
                "name"
            ],
            "properties": {
                "level": {
                    "type": "string",
                    "enum": [
                        "ABSOLUTA",
                        "MEDIA",
                        "BAJA"
                    ],
                    "example": "MEDIA"
                },
                "name": {
                    "type": "string",
                    "maxLength": 120,
                    "minLength": 1,
                    "example": "Reacciona mal al transportin"
                }
            }
        },
        "handler.registerIncompatibilityResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 5
                }
            }
        },
        "handler.removeIncompatibilityResponse": {
            "type": "object",
            "properties": {
                "dog_id": {
                    "type": "integer",
                    "example": 42
                },
                "incompatibilities": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.incompatibilityDTO"
                    }
                },
                "removed": {
                    "type": "boolean",
                    "example": true
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
